apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-db-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user-db
    template:
        metadata:
            labels:
                app: user-db
        spec:
            containers:
                - image: "ds_lab4_user-db:latest"
                  name: user-db
                  ports:
                      - containerPort: 5432
                  imagePullPolicy: Never
                  env:
                      - name: POSTGRES_USER
                        value: postgres
                      - name: POSTGRES_PASSWORD
                        value: postgres
                      - name: POSTGRES_DB
                        value: postgres
---
apiVersion: v1
kind: Service
metadata:
    name: user-db
spec:
    selector:
        app: user-db
    ports:
        - port: 5432
          targetPort: 5432
