apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-service
  template:
    metadata:
      labels:
        app: car-service
    spec:
      containers:
        - name: car-service
          image: "ds_lab4_car-service:latest"
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: API_SECRET_KEY
              value: "my_secret_key"
            - name: USER_SERVICE_HOST
              value: "user-service"
            - name: CAR_SERVICE_HOST
              value: "car-service"
            - name: LOCATION_SERVICE_HOST
              value: "location-service"
            - name: ORDER_SERVICE_HOST
              value: "order-service"
            - name: HTTP_PORT
              value: "8080"
            - name: REST_COMMUNICATION
              value: "0"
            - name: GRPC_COMMUNICATION
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: car-service
spec:
  selector:
    app: car-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
