apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: "ds_lab4_server:latest"
          ports:
            - containerPort: 8090
          imagePullPolicy: Never
          env:
            - name: SERVER_PORT
              value: "8090"
            - name: API_SECRET_KEY
              value: "my_secret_key"
            - name: USER_SERVICE_HOST
              value: "user-service"
            - name: CAR_SERVICE_HOST
              value: "car-service"
            - name: LOCATION_SERVICE_HOST
              value: "location-service"
            - name: ORDER_SERVICE_HOST
              value: "order-service"
            - name: HTTP_PORT
              value: "8080"
            - name: GRPC_PORT
              value: "9090"
            - name: REST_COMMUNICATION
              value: "0"
            - name: GRPC_COMMUNICATION
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - port: 8090
      targetPort: 8090
  type: LoadBalancer
