apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-service-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user-service
    template:
        metadata:
            labels:
                app: user-service
        spec:
            containers:
                - image: "ds_lab4_user-service:latest"
                  name: user-service
                  ports:
                      - containerPort: 8080
                  imagePullPolicy: Never
                  env:
                      - name: SERVER_PORT
                        value: "8080"
                      - name: API_SECRET_KEY
                        value: "my_secret_key"
                      - name: USER_SERVICE_HOST
                        value: "user-service"
                      - name: CAR_SERVICE_HOST
                        value: "car-service"
                      - name: LOCATION_SERVICE_HOST
                        value: "location-service"
                      - name: ORDER_SERVICE_HOST
                        value: "order-service"
                      - name: HTTP_PORT
                        value: "8080"
                      - name: GRPC_PORT
                        value: "9090"
                      - name: REST_COMMUNICATION
                        value: "1"
                      - name: GRPC_COMMUNICATION
                        value: "0"
---
apiVersion: v1
kind: Service
metadata:
    name: user-service
spec:
    selector:
        app: user-service
    ports:
        - port: 8080
          targetPort: 8080
    type: ClusterIP
